# Generated by Django 5.1.4 on 2025-01-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentSection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentAll',
        ),
    ]
