# Generated by Django 5.1.4 on 2025-01-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentSection', '0003_remove_commentall_name_commentall_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAll',
        ),
    ]
