# Generated by Django 5.1.4 on 2025-01-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentSection', '0004_delete_commentall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_description',
            new_name='newPost',
        ),
    ]
